// slides/060-vue/src/App.vue
<script setup>
import { computed, ref } from 'vue';
const count = ref(0);
const triple = computed(() => count.value * 3)
const isTripleEven = computed(() => count.value % 2 === 0)
</script>

<template>
  <p>Count: {{count}}</p>
  <p>Triple: {{triple}}</p>
  <p>Is triple even: {{isTripleEven ? 'yes' : 'no'}}</p>
  <p><button @click="count++">+1</button></p>
</template>

// slides/050-react/src/App.js
import { useState } from 'react';

function App() {
  const [count, setCount] = useState(0);
  const triple = count * 3
  const isTripleEven = triple % 2 === 0;

  return (
    <div>
      <p>Count: {count}</p>
      <p>Triple: {triple}</p>
      <p>Is triple even: {isTripleEven ? 'yes' : 'no'}</p>
      <p><button onClick={() => setCount(count + 1)}>+1</button></p>
    </div>
  );
}

export default App;
